### ISSUE TITLE
Rio Terminal

### ISSUE THREAD

**Issue by milkowski** [moktavizen/terminal-benchmark#1]
Please add Rio terminal benchmarks to the suite:
https://raphamorim.io/rio/
https://github.com/raphamorim/rio

**Comment by moktavizen** [comment]
Unfortunately, it crashed on my machine.

```sh
❯ rio
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sugarloaf-0.2.2/src/context/mod.rs:101:10:
Request adapter
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: segmentation fault (core dumped)  rio
```

**Comment by milkowski** [comment]
Maybe switching to GL backend will help: https://raphamorim.io/rio/docs/config/renderer/

**Comment by moktavizen** [comment]
Still panicked

```
❯ rio
thread 'main' panicked at sugarloaf/src/context/mod.rs:92:55:
called `Result::unwrap()` on an `Err` value: CreateSurfaceError { inner: Hal(FailedToCreateSurfaceForAnyBackend({})) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: segmentation fault (core dumped)  rio

❯ rio -V
rioterm 0.2.12
```
